name: CA for CICD
env:
  NAME: 'MYAT THIHA NAING'
on:
  push:
    branches:
      - 'release/v*.*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:


      - name: Print my name
        run: echo "I AM $NAME"


      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Railway Installation
        run: npm i -g @railway/cli

      - name: Deploy Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}


      
        



