name: CA for CICD

on:
  push:
    branches:
      - 'release/v*.*'

env:
  NAME: MYAT THIHA NAING
  EMAIL: e112943@u.nus.edu
  REPO: git@github.com:MyatThihaNaing-mthn/CICD-Assignment.git
  MATRIC: A0269560W

#this line is added just to test my commit message
#whats going on
jobs:
  build:
    
    if: startsWith(github.event.head_commit.message, '#norun') != true
    runs-on: ubuntu-latest
    steps:
    

      - name: Print my name
        run: echo "$NAME $EMAIL $REPO"
        



      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Railway Installation
        run: npm i -g @railway/cli

      - name: Deploy Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
      
      - name: Send message to slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id : 'C05552HCNRY' 
          payload: |
            
            {
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "CICD Submission"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Name:* ${{env.NAME}}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Email:* ${{env.EMAIL}}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Matricultaion:* ${{env.MATRIC}}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Repository:*\n <${{env.REPO}}>"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "<https://snotty-rhythm-production.up.railway.app/>"
                    },
                    "accessory": {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Go",
                        "emoji": true
                      },
                      "url": "https://snotty-rhythm-production.up.railway.app/",
                      "action_id": "button-action"
                    }
                  }
                ]
            }
            
            

        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          
        if: always()






      
        



