name: CA for CICD

on:
  push:
    branches:
      - 'release/v*.*'

env:
  NAME: MYAT THIHA NAING
  EMAIL: e112943@u.nus.edu
  REPO: git@github.com:MyatThihaNaing-mthn/CICD-Assignment.git

#this line is added just to test my commit message
#whats going on
jobs:
  build:
    
    if: startsWith(github.event.head_commit.message, '#norun') != true
    runs-on: ubuntu-latest
    steps:
    

      - name: Print my name
        run: echo "$NAME $EMAIL $REPO"
        



      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Railway Installation
        run: npm i -g @railway/cli

      - name: Deploy Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
      
#      - name: Notify in the slack channel
#        uses: rtCamp/action-slack-notify@v2
#         env:
#            SLACK_USERNAME: MYAT THIHA
#            SLACK_TITLE: CA TESTING
#            SLACK_MESSAGE: just for testing
#            SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}


      
        



