name: CA for CICD

on:
  push:
    branches:
      - 'release/v*.*'

env:
  NAME: MYAT THIHA NAING
  EMAIL: e112943@u.nus.edu
  REPO: git@github.com:MyatThihaNaing-mthn/CICD-Assignment.git
  MATRIC: A0269560W

#this line is added just to test my commit message
#whats going on
jobs:
  build:
    
    if: startsWith(github.event.head_commit.message, '#norun') != true
    runs-on: ubuntu-latest
    steps:
    

      - name: Print my name
        run: echo "$NAME $EMAIL $REPO"
        



      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Railway Installation
        run: npm i -g @railway/cli

      - name: Deploy Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
      
      - name: Send message to slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with: 
          payload: |
            {
              "text": "test"
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "CICD Submission"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name:* Test"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Email:* test"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Matricultaion:* abc122"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n <https://www.google.com>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://www.google.com>"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Go",
                      "emoji": true
                    },
                    "url": "https://google.com",
                    "action_id": "button-action"
                  }
                }
            }  ]

        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          APP_URL: ${{secrets.APP_URL}}
        if: always()






      
        



