name: CA for CICD

on:
  push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Railway Installation
        run: npm i -g @railway/cli

      - name: Deploy Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}

      
        




