name: CA for CICD

on:
  push:
    branches:
      - 'release/v*.*'

#this line is added just to test my commit message
#changes are made 
#Now, this is show time
jobs:
  build:
    
    if: startsWith(github.event.head_commit.message, '#norun') != true
    runs-on: ubuntu-latest
    steps:


      - name: Print my name
        run: echo "$myName, $myMail, $myRepo, $myMetri "
        env:
          myName: ${{secrets.NAME}}
          myMail: ${{secrets.EMAIL}}
          myRepo: ${{secrets.REPO}}
          myMetri: ${{secrets.METRI}}


      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Railway Installation
        run: npm i -g @railway/cli

      - name: Deploy Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}


      
        



