name: CA for CICD

on:
  push:
    branches:
      - 'release/v*.*'

env:
  NAME: MYAT THIHA NAING
  EMAIL: e112943@u.nus.edu
  REPO: git@github.com:MyatThihaNaing-mthn/CICD-Assignment.git
  MATRIC: A0269560W

#this line is added just to test my commit message
#whats going on
jobs:
  build:
    
    if: startsWith(github.event.head_commit.message, '#norun') != true
    runs-on: ubuntu-latest
    steps:
    

      - name: Print my name
        run: echo "$NAME $EMAIL $REPO"
        



      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Railway Installation
        run: npm i -g @railway/cli

      - name: Deploy Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
      
      - name: Send message to slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with: 
          payload: |
            {
              "text": "GitHub Action build result",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "test...."
                  }
                }
              ]
            }
            

        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          APP_URL: ${{secrets.APP_URL}}
        if: always()






      
        



